# Hello Application ClusterIP
apiVersion: v1
kind: Service
metadata:
    name: hello-svc
    annotations:
      cloud.google.com/neg: '{"ingress": true}'
spec:
    type: ClusterIP
    selector:
        app: hello
    ports:
      - protocol: TCP
        port: 9080
        targetPort: 80
