apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gke-Ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
#     networking.gke.io/v1beta1.FrontendConfig: "frontendconfig"
#     static-ip: xx.xx.xx.xx
spec:
    rules:
    - http:
        paths:
        - path: /greeting
            backend:
            serviceName: hello-svc
            servicePort: 9080

---
# apiVersion: networking.gke.io/v1beta1
# kind: FrontendConfig
# metadata:
#     name: my-frontend-config
# spec:
#     sslPolicy: gke-ingress-ssl-policy
