apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gke-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: hellosign-svc
          servicePort: 80

---
# apiVersion: networking.gke.io/v1beta1
# kind: FrontendConfig
# metadata:
#     name: my-frontend-config
# spec:
#     sslPolicy: gke-ingress-ssl-policy
